# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "ethan bailey"
description: "i'm an NYC based musician and software developer. i make music and build the tools to make it."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ebai.github.io" # the base hostname & protocol for your site, e.g. https://example.com
linkedin_link: 'https://www.linkedin.com/in/ethan-bailey-a94240127/'
github_username: 'ebai101'
spotify_link: 'https://open.spotify.com/artist/1pvckjRfnPNJkH7YlrKgv2?si=rs8gyP1NRBOBJZ_Ef-Ej7g'

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems

### Phantom settings
footer_text: '© 2020 ethan bailey'
admin_name: 'ethan bailey'
google_analytics: "UA-168664341-1" # Update with your own tracking ID
enable_contact: true

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'home' }
  - { url: '/about', text: 'about' }
  - { url: 'https://drive.google.com/file/d/1cosCKSEGrq1A3Z4IacNtBbuhJxzjNXw3/view?usp=sharing', text: 'resume'}
